---

- name: Archive the build directory
  ansible.builtin.command:
    cmd: "tar -czf {{archive_file}} -C {{ build_dir }} ."
  delegate_to: localhost

- name: Copy file with owner and permission
  ansible.builtin.copy:
    src   : "{{archive_file}}"
    dest  : "{{remote_dir}}"
    owner : frontend
    group : frontend
    mode  : '0644' 

- name: Finding .tar.gz found_files
  ansible.builtin.find:
    paths: "{{ remote_dir }}"
    patterns: '*.tar.gz'
  register: found_files

- name: Debugging the .tar.gz file
  ansible.builtin.debug:
    var: found_files

- name: Unarchive the directory on the remote server
  ansible.builtin.unarchive:
    src: "{{ item.path }}"
    dest: "{{ remote_dir }}"
    owner: frontend
    group: frontend
    mode: '0755'
    remote_src: yes
  with_items: "{{ found_files.files }}"

- name: Clean up the archive on the remote server
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent 
  with_items: "{{ found_files.files }}" 

- name: Reload nginx to apply new configuration
  ansible.builtin.shell:
    cmd: echo {{ansible_sudo_pass}} | sudo -S nginx -s reload

